### PR TITLE
FFaker namespace and removed ruby 1.8 support

### PR DESCRIPTION
**Pull request by dannysperry**
I was bored and thought I'd help out on this project. 
* I updated the Faker module to be FFaker and got all the tests passing. 
* I also made an quick initial round of removing 1.8 support by 
  * fixing keyed hashes to the 1.9 syntax
  * using `\p{Alpha}` instead `[:alpha:]` in regex's
* updated version for the gem to 2.0, @EmmanuelOga you will need to build the .gem file and push to rubygems

### CODE REVIEW

**Comment by PikachuEXE** [comment]
:+1: for removing 1.8 support (since it no longer supported anyway)
:-1: for changing the version and release date in a PR, should be author's job :P

PR contains merge conflicts?

**Comment by dannysperry** [comment]
@PikachuEXE thanks for the heads up, open source n00b mistakes :). 
@EmmanuelOga merge conflicts fixed.

**Comment by EmmanuelOga** [comment]
Hi @dannysperry, @rocknruby is maintaining the gem these days, thanks for the PR!

**Comment by rocknruby** [comment]
Hi @dannysperry, could you please rebase your branch. thx.

**Comment by dannysperry** [comment]
Hi @rocknruby, I rebased and had to force push the changes to my branch. I'm relatively sure I did everything right, my doubt comes from this github PR stating that there are merge conflicts. There were merge conflicts when i rebased, but i fixed them all during the process. Let me know if I need to do something else.

**Comment by rocknruby** [comment]
Hi @dannysperry , unfortunately your branch isnt mergeable. Can we get in contact to solve the problem for example via. gitter. I created a chatroom: https://gitter.im/EmmanuelOga/ffaker

**Comment by rocknruby** [comment]
I close this and opened #179

**Pull request closed without merging**
